export const CONFIG = {
  legendsPrice: 39,
  benchmarkPass: 1100,
  topRate: 91,
};

export const regularOptions = [
  { label: "Copper 5 Day", price: 369, region: "West" },
  { label: "Mt. Bachelor 5 Day", price: 449, region: "West" },
  { label: "Mammoth 4 Day", price: 399, region: "West" },
  { label: "Snowbird 5 Day", price: 510, region: "West" },
  { label: "Big Sky 3 Day", price: 369, region: "West" },
  { label: "Big Sky 4 Day", price: 440, region: "West" },
  { label: "Big Sky 5 Day", price: 510, region: "West" },
  { label: "Taos 3 Day", price: 390, region: "West" },
  { label: "Taos 4 Day", price: 459, region: "West" },
  { label: "Taos 5 Day", price: 525, region: "West" },
  { label: "Banff Sunshine Village 4 Day", price: 328, region: "West" },
  { label: "Lake Louise 4 Day", price: 308, region: "West" },
  { label: "Revelstoke 4 Day", price: 348, region: "West" },
  { label: "Snowbasin 4 Day", price: 490, region: "West" },
  { label: "Snowbasin 5 Day", price: 545, region: "West" },
  { label: "Grand Targhee 4 Day", price: 399, region: "West" },
  { label: "Palisades Tahoe 4 Pack", price: 459, region: "West" },
  { label: "Vail 2 Day", price: 239, region: "West" },
  { label: "Vail 3 Day", price: 342, region: "West" },
  { label: "Vail 4 Day", price: 434, region: "West" },
  { label: "Vail 5 Day", price: 525, region: "West" },
  { label: "Breckenridge 2 Day", price: 239, region: "West" },
  { label: "Breckenridge 3 Day", price: 342, region: "West" },
  { label: "Breckenridge 4 Day", price: 434, region: "West" },
  { label: "Breckenridge 5 Day", price: 525, region: "West" },
  { label: "Beaver Creek 2 Day", price: 239, region: "West" },
  { label: "Beaver Creek 3 Day", price: 342, region: "West" },
  { label: "Beaver Creek 4 Day", price: 434, region: "West" },
  { label: "Beaver Creek 5 Day", price: 525, region: "West" },
  { label: "Park City 2 Day", price: 239, region: "West" },
  { label: "Park City 3 Day", price: 342, region: "West" },
  { label: "Park City 4 Day", price: 434, region: "West" },
  { label: "Park City 5 Day", price: 525, region: "West" },
  { label: "Keystone 2 Day", price: 187, region: "West" },
  { label: "Keystone 3 Day", price: 271, region: "West" },
  { label: "Keystone 4 Day", price: 349, region: "West" },
  { label: "Keystone 5 Day", price: 425, region: "West" },
  { label: "Heavenly Kirkwood Northstar 2 Day", price: 187, region: "West" },
  { label: "Heavenly Kirkwood Northstar 3 Day", price: 271, region: "West" },
  { label: "Heavenly Kirkwood Northstar 4 Day", price: 349, region: "West" },
  { label: "Heavenly Kirkwood Northstar 5 Day", price: 425, region: "West" },
  { label: "Stevens Pass 2 Day", price: 187, region: "West" },
  { label: "Stevens Pass 3 Day", price: 271, region: "West" },
  { label: "Stevens Pass 4 Day", price: 349, region: "West" },
  { label: "Stevens Pass 5 Day", price: 425, region: "West" },
  { label: "Loveland 2 Days", price: 144, region: "West" },
  { label: "Loveland 4 Days", price: 289, region: "West" },
  { label: "Crystal Mountain 3 Days", price: 249, region: "West" },
  { label: "Schweitzer 3 Days", price: 249, region: "West" },
  { label: "Arapahoe Basin 3 Days", price: 249, region: "West" },
  { label: "Arapahoe Basin 4 Days", price: 299, region: "West" },
  { label: "Arapahoe Basin 5 Days", price: 339, region: "West" },
  { label: "Alta Unlimited 50 Percent Off Days", price: 149, region: "West" },
  { label: "Killington 2 Days", price: 240, region: "East" },
  { label: "Killington 3 Days", price: 339, region: "East" },
  { label: "Killington 4 Days", price: 429, region: "East" },
  { label: "Sugarbush 1 Day", price: 99, region: "East" },
  { label: "Sugarbush 2 Days", price: 198, region: "East" },
  { label: "Sugarbush 3 Days", price: 297, region: "East" },
  { label: "Sugarbush 4 Days", price: 396, region: "East" },
  { label: "Sugarbush 5 Days", price: 495, region: "East" },
  { label: "Jay Peak 2 Days", price: 144, region: "East" },
  { label: "Jay Peak 4 Days", price: 289, region: "East" },
  { label: "Stowe Okemo 2 Days", price: 187, region: "East" },
  { label: "Stowe Okemo 3 Days", price: 271, region: "East" },
  { label: "Stowe Okemo 4 Days", price: 349, region: "East" },
  { label: "Stowe Okemo 5 Days", price: 425, region: "East" },
  { label: "Sugarloaf 3 Days", price: 269, region: "East" },
  { label: "Sunday River 3 Days", price: 289, region: "East" },
  { label: "Wildcat Attitash 2 Days", price: 110, region: "East" },
  { label: "Wildcat Attitash 3 Days", price: 165, region: "East" },
  { label: "Wildcat Attitash 4 Days", price: 220, region: "East" },
  { label: "Wildcat Attitash 5 Days", price: 275, region: "East" },
  { label: "Snowshoe 3 Days", price: 199, region: "East" },
  { label: "Gore Whiteface Combo 3 Days", price: 199, region: "East" },
];

export const topOptions = [
  { label: "Big Sky 3 Days - $273 - Restricted Trip Options", price: 273, topType: "top3", key: "bigsky" },
  { label: "Jackson Hole 3 Days - $273 - Restricted Trip Options", price: 273, topType: "top3", key: "jackson" },
  { label: "Snowbasin 3 Days - $273 - Restricted Trip Options", price: 273, topType: "top3", key: "snowbasin" },
  { label: "Taos 3 Days - $273 - Restricted Trip Options", price: 273, topType: "top3", key: "taos" },
  { label: "Sun Valley 3 Days - $273 - Restricted Trip Options", price: 273, topType: "top3", key: "sunvalley" },
  { label: "Aspen 3 Days - $273 - Restricted Trip Options", price: 273, topType: "top3", key: "aspen" },
  { label: "Alta 2 + Snowbird 2 Days - $364 - Restricted Trip Options", price: 364, topType: "pair", key: "alta_snowbird" },
  { label: "Sunshine 2 + Lake Louise 2 Days - $364 - Restricted Trip Options", price: 364, topType: "pair", key: "sunshine_lakelouise" },
  { label: "Jackson Hole 2 + Grand Targhee 2 Days - $364 - Restricted Trip Options", price: 364, topType: "pair", key: "jackson_gt" },
];
